// Generated by scripts/build-photos.py from scripts/photo-picks.json.
// Every photo is CC BY 2.0: credit the author and title, link the source, and
// say it was changed. Edit the picks and re-run the script, not this file.

export type PhotoCredit = {
  file: string;
  title: string;
  author: string;
  source: string;
};

export const PHOTO_LICENSE = {
  name: "CC BY 2.0",
  url: "https://creativecommons.org/licenses/by/2.0/",
};

export const PHOTO_CREDITS: PhotoCredit[] = [
  { file: "/photos/categories/fruit-veg.webp", title: "Peppers!", author: "Ian Ransley", source: "https://www.flickr.com/photos/design-dog/1105387190" },
  { file: "/photos/categories/dairy-eggs.webp", title: "Fresh Eggs", author: "J P Davidson", source: "https://www.flickr.com/photos/jpdavidsonimages/4752438108" },
  { file: "/photos/categories/bakery.webp", title: "Bread and buns", author: "TNS Sofres", source: "https://www.flickr.com/photos/124561666@N02/14396922334" },
  { file: "/photos/categories/meat-fish.webp", title: "100グラム2100円のサーロインでございます", author: "Ryosuke Hosoi", source: "https://www.flickr.com/photos/rhosoi/303340771" },
  { file: "/photos/categories/drinks.webp", title: "Crystal and I *really* like orange juice in New Orleans,  Louisiana", author: "Shane Becker", source: "https://www.flickr.com/photos/veganstraightedge/3835097172/" },
  { file: "/photos/categories/snacks.webp", title: "homemade cookies", author: "Think Draw", source: "https://www.flickr.com/photos/thinkdraw/6182804" },
  { file: "/photos/categories/pantry.webp", title: "Make your own deodorant", author: "thedabblist", source: "https://www.flickr.com/photos/64636759@N07/9669540222" },
  { file: "/photos/categories/household.webp", title: "Organic hippie crap", author: "Joshua Blount", source: "https://www.flickr.com/photos/stickwithjosh/5177208422" },
  { file: "/photos/categories/baby.webp", title: "bumGenius", author: "trenttsd", source: "https://www.flickr.com/photos/84335369@N00/2887774785" },
  { file: "/photos/categories/pharmacy.webp", title: "Pills", author: "Jamie", source: "https://www.flickr.com/photos/jamiesrabbits/5747870989" },
  { file: "/photos/products/tomatoes.webp", title: "Jersey Tomatoes", author: "Eden, Janine and Jim", source: "https://www.flickr.com/photos/edenpictures/11279110123" },
  { file: "/photos/products/bananas.webp", title: "everyone misses you, lou reed :  bananas, ferry building, san francisco (2012)", author: "torbakhopper", source: "https://www.flickr.com/photos/gazeronly/7849659582" },
  { file: "/photos/products/onions.webp", title: "Onions and green chili", author: "Johan Bichel Lindegaard", source: "https://www.flickr.com/photos/accidentdesigns/5560910594" },
  { file: "/photos/products/covo.webp", title: "cabbage like plant", author: "Iqbal Osman", source: "https://www.flickr.com/photos/82066314@N06/10345826983" },
  { file: "/photos/products/potatoes.webp", title: "Potatoes", author: "Bart Everson", source: "https://www.flickr.com/photos/editor/3549887095" },
  { file: "/photos/products/apples.webp", title: "Apples, apples, apples", author: "James Cridland", source: "https://www.flickr.com/photos/jamescridland/1305153543" },
  { file: "/photos/products/eggs.webp", title: "Ovos, Huevos, Eggs", author: "Victoria Rachitzky Hoch", source: "https://www.flickr.com/photos/viclic/272759452" },
  { file: "/photos/products/cheese.webp", title: "cheese 2 - Cabot Creamery - Baconfest 2013.jpg", author: "opacity", source: "https://www.flickr.com/photos/opacity/8669831713" },
  { file: "/photos/products/white-bread.webp", title: "Michael's Homemade Bread", author: "Katie Kuksenok", source: "https://www.flickr.com/photos/kt_kuksenok/5402793405" },
  { file: "/photos/products/brown-bread.webp", title: "Maize", author: "Janels Katlaps", source: "https://www.flickr.com/photos/smoking2much/7248252860" },
  { file: "/photos/products/buns.webp", title: "P1080130", author: "Aaron \"tango\" Tang", source: "https://www.flickr.com/photos/hahatango/5113102785" },
  { file: "/photos/products/kapenta.webp", title: "Sardines at Loule Market - Portugal (Loule)", author: "Romain MOREL", source: "https://www.flickr.com/photos/romainmo/2884507685" },
  { file: "/photos/products/boerewors.webp", title: "nineteen/three-sixty-five", author: "Laura Bittner", source: "https://www.flickr.com/photos/wolfsavard/4766578900" },
  { file: "/photos/products/water.webp", title: "Water", author: "Brian Smithson", source: "https://www.flickr.com/photos/smithser/7239957418" },
  { file: "/photos/products/mealie-meal.webp", title: "Corn. Sweet!", author: "RichardBH", source: "https://www.flickr.com/photos/rbh/14880510979" },
  { file: "/photos/products/rice.webp", title: "rice bowl", author: "georgereyes", source: "https://www.flickr.com/photos/george_reyes/391843903" },
  { file: "/photos/products/sugar.webp", title: "Sugar", author: "Melissa Wiese", source: "https://www.flickr.com/photos/42dreams/2452033439" },
  { file: "/photos/products/salt.webp", title: "sea salt", author: "mriggen", source: "https://www.flickr.com/photos/riggenransom/9290433208" },
  { file: "/photos/products/toilet-paper.webp", title: "Wipe out", author: "Kyknoord", source: "https://www.flickr.com/photos/kyknoord/390035987" },
  { file: "/photos/products/plasters.webp", title: "Plasters", author: "Medisave UK", source: "https://www.flickr.com/photos/107621760@N03/10668646004" },
];
