#!/usr/bin/env python3
"""Rebuild public/photos and lib/photo-credits.ts from scripts/photo-picks.json.

Every pick is a Flickr photo from Google's Open Images dataset, licensed
CC BY 2.0. Each entry records the image, the crop box (normalised, from the
dataset's human-drawn bounding boxes) and the attribution the licence needs.

    pip install pillow
    python3 scripts/build-photos.py

Images come from the dataset's public S3 mirror, so no Flickr access is needed.
"""

import io
import json
import pathlib
import urllib.request

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
PICKS = json.loads((ROOT / "scripts/photo-picks.json").read_text())
OUT = ROOT / "public/photos"
S3 = "https://open-images-dataset.s3.amazonaws.com/{subset}/{image_id}.jpg"


def fetch(pick):
    with urllib.request.urlopen(S3.format(**pick), timeout=60) as r:
        im = Image.open(io.BytesIO(r.read())).convert("RGB")
    if pick["rotation"] and float(pick["rotation"]):
        # The dataset gives the clockwise rotation needed to display it upright.
        im = im.rotate(-float(pick["rotation"]), expand=True)
    return im


def square_crop(im, box, pad=1.08):
    """Square crop centred on the labelled object, or the centre of the frame."""
    w, h = im.size
    if box:
        x0, y0, x1, y1 = box
        cx, cy = (x0 + x1) / 2 * w, (y0 + y1) / 2 * h
        side = max((x1 - x0) * w, (y1 - y0) * h) * pad
    else:
        cx, cy, side = w / 2, h / 2, min(w, h)
    side = min(side, w, h)
    left = min(max(cx - side / 2, 0), w - side)
    top = min(max(cy - side / 2, 0), h - side)
    return im.crop((int(left), int(top), int(left + side), int(top + side)))


def credits_module(picks):
    rows = "\n".join(
        "  { file: %s, title: %s, author: %s, source: %s },"
        % tuple(
            json.dumps(v, ensure_ascii=False)
            for v in ("/photos/" + p["out"], p["title"], p["author"], p["source"])
        )
        for p in picks
    )
    return f"""// Generated by scripts/build-photos.py from scripts/photo-picks.json.
// Every photo is CC BY 2.0: credit the author and title, link the source, and
// say it was changed. Edit the picks and re-run the script, not this file.

export type PhotoCredit = {{
  file: string;
  title: string;
  author: string;
  source: string;
}};

export const PHOTO_LICENSE = {{
  name: "CC BY 2.0",
  url: "https://creativecommons.org/licenses/by/2.0/",
}};

export const PHOTO_CREDITS: PhotoCredit[] = [
{rows}
];
"""


def main():
    for pick in PICKS:
        dest = OUT / pick["out"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        im = square_crop(fetch(pick), pick["box"])
        im.resize((pick["size"], pick["size"]), Image.LANCZOS).save(
            dest, "WEBP", quality=80, method=6
        )
        print(f"{dest.relative_to(ROOT)}  {dest.stat().st_size // 1024} KB")
    (ROOT / "lib/photo-credits.ts").write_text(credits_module(PICKS))


if __name__ == "__main__":
    main()
